# ETL with Python

In [2]:
import pandas as pd
import numpy as np 


customers=pd.DataFrame([["C001", "Ahmed Benali", "Fes", "Morocco"],
    ["C002", "Sara Alaoui", "Rabat", "Morocco"],
    ["C003", "Youssef Amrani", "Casablanca", "Morocco"],
    ["C004", "Salma Idrissi", "Marrakech", "Morocco"],
    ["C005", "Omar El Fassi", "Tangier", "Morocco"],
    ["C006", "Nadia Zahra", "Agadir", "Morocco"],
    ["C007", "Karim Mansouri", "Meknes", "Morocco"],
    ["C008", "Lina Bennani", "Oujda", "Morocco"],
    ["C009", "Hicham Tazi", "Kenitra", "Morocco"],
    ["C010", "Imane Chraibi", "Tetouan", "Morocco"],],columns=["customer_id","name","city","country"])

products = pd.DataFrame([
    ["P001", "Laptop", "Electronics", 800.00],
    ["P002", "Wireless Mouse", "Accessories", 25.00],
    ["P003", "Keyboard", "Accessories", 45.00],
    ["P004", "Monitor", "Electronics", 250.00],
    ["P005", "USB-C Hub", "Accessories", 35.00],
    ["P006", "Headphones", "Electronics", 90.00],
    ["P007", "Webcam", "Electronics", 70.00],
    ["P008", "Office Chair", "Furniture", 180.00],
    ["P009", "Desk Lamp", "Furniture", 40.00],
    ["P010", "External SSD", "Storage", 120.00],
], columns=["product_id", "product_name", "category", "price"])

orders = pd.DataFrame([
    ["O001", "2026-01-05", "C001", "P001", 1],
    ["O002", "2026-01-06", "C002", "P002", 3],
    ["O003", "2026-01-08", "C003", "P004", 2],
    ["O004", "2026-01-10", "C004", "P006", 1],
    ["O005", "2026-01-12", "C005", "P003", 2],
    ["O006", "2026-01-15", "C006", "P008", 1],
    ["O007", "2026-01-18", "C007", "P005", 4],
    ["O008", "2026-01-21", "C008", "P010", 2],
    ["O009", "2026-01-25", "C009", "P007", 2],
    ["O010", "2026-01-28", "C010", "P009", 3],
    ["O011", "2026-02-02", "C001", "P004", 1],
    ["O012", "2026-02-05", "C002", "P006", 2],
    ["O013", "2026-02-09", "C003", "P001", 1],
    ["O014", "2026-02-13", "C004", "P002", 5],
    ["O015", "2026-02-17", "C005", "P008", 1],
    ["O016", "2026-02-20", "C006", "P010", 3],
    ["O017", "2026-02-24", "C007", "P003", 2],
    ["O018", "2026-02-27", "C008", "P005", 2],
    ["O019", "2026-03-03", "C009", "P001", 2],
    ["O020", "2026-03-07", "C010", "P006", 1],
    ["O021", "2026-03-11", "C001", "P008", 2],
    ["O022", "2026-03-15", "C002", "P009", 4],
    ["O023", "2026-03-18", "C003", "P010", 1],
    ["O024", "2026-03-22", "C004", "P007", 2],
    ["O025", "2026-03-27", "C005", "P004", 1],
    ["O026", "2026-04-02", "C006", "P002", 6],
    ["O027", "2026-04-06", "C007", "P001", 1],
    ["O028", "2026-04-12", "C008", "P006", 2],
    ["O029", "2026-04-19", "C009", "P003", 3],
    ["O030", "2026-04-25", "C010", "P010", 2],
], columns=["order_id", "order_date", "customer_id", "product_id", "quantity"])

In [7]:
df1=pd.read_csv("data\customers.csv", dtype={"customer_id": "string"}
)
# df1.head()
# df1.duplicated().sum()
# df1.shape
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    10 non-null     string
 1   customer_name  10 non-null     object
 2   city           10 non-null     object
 3   country        10 non-null     object
dtypes: object(3), string(1)
memory usage: 452.0+ bytes

In [8]:
df2=pd.read_csv("data\Products.csv")
df2.head()

  product_id    product_name     category  unit_price
0       P001          Laptop  Electronics       800.0
1       P002  Wireless Mouse  Accessories        25.0
2       P003        Keyboard  Accessories        45.0
3       P004         Monitor  Electronics       250.0
4       P005       USB-C Hub  Accessories        35.0

In [5]:
df2.info()
df2.shape
# df2.isnull().sum()
# df2['price']=df2['price'].fillna(100)
# df2.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    10 non-null     object
 1   product_name  10 non-null     object
 2   category      10 non-null     object
 3   unit_price    10 non-null     float64
dtypes: float64(1), object(3)
memory usage: 452.0+ bytes

(10, 4)

In [8]:
df3=pd.read_csv("data\\orders.csv")
df3

  order_id  order_date customer_id product_id  quantity  total_amount
0     O001  2026-01-05        C001       P001         1         800.0
1     O002  2026-01-06        C002       P002         3          75.0
2     O003  2026-01-08        C003       P004         2          90.0
3     O004  2026-01-10        C004       P006         1         250.0
4     O005  2026-01-12        C005       P003         2          70.0
5     O006  2026-01-15        C006       P008         1          90.0
6     O007  2026-01-18        C007       P005         4         280.0
7     O008  2026-01-21        C008       P010         2         360.0
8     O009  2026-01-25        C009       P007         2          80.0
9     O010  2026-01-28        C010       P009         3         360.0

In [11]:
df3['order_date']=pd.to_datetime(df3['order_date'], errors="coerce")
df3.shape
df3.info()
df3.isnull().sum()
df3.fillna(0)
df3.duplicated().sum()
df3.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   order_date    10 non-null     datetime64[ns]
 2   customer_id   10 non-null     object
 3   product_id    10 non-null     object
 4   quantity      10 non-null     int64
 5   total_amount  10 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 612.0+ bytes

(10, 6)

In [12]:
df3

  order_id order_date customer_id product_id  quantity  total_amount
0     O001 2026-01-05        C001       P001         1         800.0
1     O002 2026-01-06        C002       P002         3          75.0
2     O003 2026-01-08        C003       P004         2          90.0
3     O004 2026-01-10        C004       P006         1         250.0
4     O005 2026-01-12        C005       P003         2          70.0
5     O006 2026-01-15        C006       P008         1          90.0
6     O007 2026-01-18        C007       P005         4         280.0
7     O008 2026-01-21        C008       P010         2         360.0
8     O009 2026-01-25        C009       P007         2          80.0
9     O010 2026-01-28        C010       P009         3         360.0

In [13]:
df3.to_csv("data\\orders.csv",index=False)

# DataWarhouse

In [ ]:
%pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

# connect to DataBase

In [4]:
from sqlalchemy import create_engine

from urllib.parse import quote_plus
password=quote_plus("B#@01$30%A_1")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/Sales_Dw"
)

In [5]:
with engine.connect() as conn:
    print("Connected!")

Connected!

# load data into DataWarhouse

In [61]:
df3["order_date"] = pd.to_datetime(df3["order_date"])

date = df3[["order_date"]].drop_duplicates()

date["date_key"] = date["order_date"].dt.strftime("%Y%m%d").astype(int)
date["full_date"] = date["order_date"]
date["year"] = date["order_date"].dt.year
date["month"] = date["order_date"].dt.month
date["day"] = date["order_date"].dt.day

date = date[
    ["date_key", "full_date", "year", "month", "day"]
]

In [62]:
df1.to_sql(
    "dim_customer",
    engine,
    if_exists="append",
    index=False
)

df2.to_sql(
    "dim_product",
    engine,
    if_exists="append",
    index=False
)

date.to_sql(
    "dim_date",
    engine,
    if_exists="append",
    index=False
)

10

In [23]:
# Get keys form tables in database
dim_customer = pd.read_sql(
    "SELECT customer_key, customer_id FROM dim_customer",
    engine
)

dim_product = pd.read_sql(
    "SELECT product_key, product_id FROM dim_product",
    engine
)

dim_date=pd.read_sql(
    "SELECT full_date , day FROM dim_date",
    engine
)

In [24]:
# Join 3 table into fact

fact = df3.merge(
    dim_customer,
    on="customer_id",
    how='left'
).merge(
    dim_product,
    on="product_id",
    how='left'
)

fact

,order_id,order_date,customer_id,product_id,quantity,total_amount,customer_key,product_key
0,O001,2026-01-05,C001,P001,1,800.0,1,1
1,O002,2026-01-06,C002,P002,3,75.0,2,2
2,O003,2026-01-08,C003,P004,2,90.0,3,4
3,O004,2026-01-10,C004,P006,1,250.0,4,6
4,O005,2026-01-12,C005,P003,2,70.0,5,3
5,O006,2026-01-15,C006,P008,1,90.0,6,8
6,O007,2026-01-18,C007,P005,4,280.0,7,5
7,O008,2026-01-21,C008,P010,2,360.0,8,10
8,O009,2026-01-25,C009,P007,2,80.0,9,7
9,O010,2026-01-28,C010,P009,3,360.0,10,9

In [65]:
fact = fact[
    [
        "order_id",
        "customer_key",
        "product_key",
        "date_key",
        "quantity",
        "total_amount"
    ]
]

In [66]:
fact.to_sql(
     "fact_orders",
     engine,
     if_exists="append",
     index=False
)

10